### ISSUE TITLE
自动隐藏任务栏导致窗口最大化后无法显示底部的任务栏

### ISSUE THREAD

**Issue by zhiyiYo** [hcaihao/StyleWindow#1]
如果开启了自动隐藏任务栏功能，无边框窗口最大化后会挡住底部2个像素的任务栏边框，导致鼠标移动到底部却无法弹出任务栏。而且如果最大化后点击最小化按钮，窗口最小化的动画也没掉了。像 VSCode 或者谷歌浏览器就没有这个问题：
![demo](https://user-images.githubusercontent.com/65096819/174429618-1811210a-5753-4d72-8beb-62a4b218fe78.gif)

我修改了一下处理 `WM_NCCALCSIZE` 消息的代码，可以从 PyQt-Frameless-Window 的 [beta](https://github.com/zhiyiYo/PyQt-Frameless-Window/tree/beta) 分支获取最新代码，但是不知道在多屏情况下效果如何，代码应该很容易转换成 cpp 代码，感激不尽。

**Comment by 564398053** [comment]
来信已收到，谢谢

**Comment by hcaihao** [comment]
感谢同步，抽时间我update一下
